name: Deploy to EKS

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
  EKS_CLUSTER_NAME: my-eks-cluster
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: your-registry
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pchmykh/phpapp:latest

            #      - name: Apply Kubernetes manifests
            #        uses: kubernetes-actions/kubectl@v1.2.1
            #        with:
            #          args: apply -f ./path/to/your/k8s/manifests
            #          kubeconfig: ${{ secrets.KUBECONFIG }}

