name: Deploy to EKS
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: pfw2-cluster
    #  IMAGE_TAG: latest

jobs:
  deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: 097084951758.dkr.ecr.us-east-1.amazonaws.com/pfw2
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pchmykh/phpapp:latest

      - name: Apply Kubernetes manifests
        uses: kubernetes-actions/kubectl@v1.2.1
        with:
          args: apply -f phpapp.yaml
          kubeconfig: ${{ secrets.KUBECONFIG }}

