name: GitHub Actions building docker image
on: [push]
jobs:
  docker_image_creation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: dh login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: pchmykh/pfw2:latest

  aws_credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-output: json

  aws_ecr_auth:
    runs-on: ubuntu-latest
    needs: aws_credentials
    uses: aws-actions/amazon-ecr-login@v1

  deploy:
    runs-on: ubuntu-latest
    needs: docker_image_creation
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f phpapp.yaml
